### ISSUE TITLE
Compatibility with PF2e Kingmaker Tools foundry app

### ISSUE THREAD

**Issue by Fyrexian** [therealguy90/foundrytodiscord#14]
I mainly want the kingdom sheet's rolls from this module to appear in discord, so that we can do kingdom turns outside the session, but allow others to still see what's going on. However, it does not seem compatible as the custom rolls seem to be blank in discord.

https://github.com/BernhardPosselt/pf2e-kingmaker-tools

![image](https://github.com/therealguy90/foundrytodiscord/assets/47077661/52470c8f-6217-4932-91ac-16a4b4edc8ed)
![image](https://github.com/therealguy90/foundrytodiscord/assets/47077661/49211b77-27e1-4f79-88c8-1aa4754fb380)
![image](https://github.com/therealguy90/foundrytodiscord/assets/47077661/f1cbb4b0-7e88-4a6a-8c22-20f917a568c2)

**Comment by therealguy90** [comment]
Oh, interesting. Looks like the Kingmaker module is tripping off isRoll on the kingmaker module rolls, but the actual displayed message is that of a chat card. I'll work on this.

**Comment by therealguy90** [comment]
Update: I see. There's two issues here:
- Since the actor containing the kingdom sheet was essentially not a "PF2e" actor, the flags didn't exist, causing a problem with the parser. 
- The degree of success was labeled as a roll, even though it didn't contain any rolls. 

If you can grab the zip from my latest commit, it'll be fixed there, but this will be included in the next release. Here is the output fixed in commit 15d995a1a1d888788462edfb696abf998bcb4407.
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/211a33dc-4bbe-4792-9301-2cfa203a394b)
