### ISSUE TITLE
Journal Entries?

### ISSUE THREAD

**Issue by SecretSquirrel77** [therealguy90/foundrytodiscord#16]
This module is really interesting! Is there a way to port journal entries to discord in even a basic way (perhaps the text of a journal entry and the related image)? 
Outside of copy/paste of the journal entry contents into discord manually, a way to export would be amazing. A possible use case is for a module like Forien's Quest Log, which would allow a GM to port the quest contents into a thread or threads.
Not sure how feasible, but thought I would ask.

Thanks!

**Comment by therealguy90** [comment]
Have you tried [Quick Send to Chat](https://foundryvtt.com/packages/roll-from-compendium)? It can send a journal entry to chat. I don't know how good it will look, but it's *a* solution. Let me know if it's sufficient to be used with Foundry to Discord. Having a dedicated button to send it to Discord could still be viable, yet a bit labor-intensive, though.

**Comment by therealguy90** [comment]
Actually, I've just now found out that it sends the journal entry as a whisper... That's not great. I'll look into this FR and see how viable it is.

**Comment by therealguy90** [comment]
Alright. This looks easy to implement, with a small restriction, of course, since we're talking about converting a Journal page to a Discord message:

"Text" type journals will not include images embedded into the html of the text content 
For this, I'll add a button to send image popouts directly to discord, like this:
![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/0b936b98-d9ef-4ebf-b808-7a4eeb95a99e)

**Comment by SecretSquirrel77** [comment]
Awesome! I will play around with it!
