### ISSUE TITLE
Include Dice Formulas in Messages

### ISSUE THREAD

**Issue by MrVauxs** [therealguy90/foundrytodiscord#18]
**Is your feature request related to a problem? Please describe.**
When rolling in PF2e, the only thing that is sent to Discord is the final result. You may roll "2d10+2d6+1d10", but you only see a "22"

**Describe the solution you'd like**
Send the formula that was used to roll the dice. It can be easily accessed from `rolls[index].formula`

**Additional context**
You may want to provide a setting to hide these (?)

**Comment by therealguy90** [comment]
Was gonna work on this, actually :P 
The code from the generic rolling message (using /r) is still using legacy code from DiscordConnect that I never bothered to change, but I'm doing a ton of code refactoring and cleaning right now, and this is on the to-do list.
The plan for this is to keep the code and show the roll formula if the origin is from a player user.
Should be done in next release.

**Comment by therealguy90** [comment]
Oh, to clarify, by the way, are you referring to the way normal rolls (ex. /r 2d10+2d6+1d10) results are grouped up into one value, or specifically showing damage roll formulas in PF2e? Example, instead of the current implementation:

**Damage Roll - Weapon Name (Hit)**
 `[Trait1] [Trait2]`

**Result:__22__**||(Damage breakdown goes here)||

The request is to change this to:

**Damage Roll - Weapon Name (Hit)**
 `[Trait1] [Trait2]`

**2d10 damagetype + 2d6 damagetype + 1d10 damagetype**

**Result:__22__**||(Damage breakdown goes here)||

This is what you're referring to, correct? Either way, I'm going to work on both /r and PF2e damage rolls like this.

**Comment by MrVauxs** [comment]
Specifically damage formulas, I barely ever use `/r` haha. But looks good.

**Comment by therealguy90** [comment]
Done in 2593814351fc0a224f5b87bcf90ee8f432db45d1.
