### ISSUE TITLE
Attack rolls not showing dice rolls/numbers + gm prrivate chat not working

### ISSUE THREAD

**Issue by weefreemen** [therealguy90/foundrytodiscord#22]
**Describe the bug**
Before answering the questions on this template, are you on the latest release of this module?
- Is the bug caused by a conflict with this module?
- Is this module throwing an error?
- Is the message from the webhook not like you expected?

**To Reproduce**
Steps to reproduce the behaviour:
1. Make an attack roll
2. Check Discord
3. Voila

**Expected behaviour**
I expected the rolls to be shown not for it to show "Miss" or "Hit", as I'm trying to provide a viewer of my dnd game the ability to collect dice roll data etc.
 
Is there something I am doing wrong?

Also, whilst in "Private GM Roll" it doesn't hide my text messages like it should and I have to manually right click and make private which is pretty scuffed? :s

**Screenshots**
https://i.imgur.com/3QnHXem.png
https://i.imgur.com/rTRjRXo.png

**Additional context**

**Comment by therealguy90** [comment]
This does not involve a bug in Foundry to Discord. The reason it shows as "Misses" or "Hits" is because that's what the player sees. I advise you to change your midi-qol settings to unhide roll metagame information. If you've read the intent of this module carefully, what the module will show is only what the players see. From your perspective, it would show the roll information, but your midi-qol settings specify that will be hidden from your players, thus Foundry to Discord will also hide it.

Regarding "Private GM Roll" mode, chat isn't automatically hidden. This is core behavior and does not concern this module. Whispering to yourself, however, will hide the chat message from others.

**Comment by weefreemen** [comment]
Hi Loki,

Thanks for the response, you're correct. It is Midi that is hiding that
information, but, reason for me not catching onto that is because it was
only meant to hide the GM rolls, which is what it does from a player's
perspective.

I can just run without hiding my stuff that is fine.

One issue I came across is that with rolls made with advantage/disadvantage
it doesn't show both rolls, is there anyway for me to change that?

Also, it doesn't show the base rolled number for attack rolls but does for
skill/ability checks.

Reason I'm looking to be able to have this information shown is that we're
trying to record as many of the dice rolls as possible, any suggestions? :)

Great module by the way, thank you

**Comment by therealguy90** [comment]
Unfortunately, midi attack rolls don't provide the full roll result through the chat message, so this module can't grab it, unlike skill checks where the roll results are given through the ChatMessage object. If you have "Show roll formulas where applicable" enabled on Foundry to Discord, you can pretty much just infer what the dice roll could be based on what the result is, including advantage and disadvantage. Sorry I can't help with this, but midi's a difficult integration for this module as it is.

**Comment by weefreemen** [comment]
Hey Loki,

That makes a lot of sense, thank you.

I may end up moving away from the module anyway as it has a few
issues/conflicts.

Appreciate the response!

**Comment by therealguy90** [comment]
Reopening this due to midi now providing rolls to generate roll breakdowns per dice. This is now possible to do with midi-qol's beta version 11.4.x for dnd5e 3.x. Will be included in next release with the following scope:

- Player rolls will always be displayed with formulas and roll values
- GM rolls will follow midi-qol setting "GM Roll details hiding"

**Comment by weefreemen** [comment]
That is awesome!

Let me know if you need anything from me to help
