### ISSUE TITLE
Auto-Send Item to Discord when message is just an UUID tag

### ISSUE THREAD

**Issue by MrVauxs** [therealguy90/foundrytodiscord#23]
**Is your feature request related to a problem? Please describe.**
Often I use Quick Insert to put a tag in chat for a reference a feature or sheet. This is effectively me sending to chat the feature but requiring the player to click on it first. Unfortunately that means that Foundry to Discord simply sends the tag and not the item itself.

**Describe the solution you'd like**
It would be lovely to have a setting that when enabled, automatically proceeds to send the item to Discord if a message only contains the UUID tag.

**Describe alternatives you've considered**
Doing it all manually by having another module add a "Send" button on some sheets and send them to both chat and Discord that way, and using the "Send Current Page to Discord" on Journal Entries.

**Additional context**
![image](https://github.com/therealguy90/foundrytodiscord/assets/32039708/633e320e-b7b0-423c-ad90-acb8c1cd5b47)
![image](https://github.com/therealguy90/foundrytodiscord/assets/32039708/d3640036-6f1c-48a7-996d-457c7b7c6361)

After manually going to the item: 
![image](https://github.com/therealguy90/foundrytodiscord/assets/32039708/36f3efca-a4f2-46ad-85e1-324eaedeccfc)

**Comment by therealguy90** [comment]
Hmm... Items are doable, but journal links are a little more complicated, since I can only fit 10 embeds onto one message. I could limit it to 10, of course, 

How about [Quick Send to Chat](https://foundryvtt.com/packages/roll-from-compendium) as an alternative? It's what I use for my games if I need to send an item to chat from the item app window. It's an extra click, but it's good enough for me, at least. If it's cluttery for you, as you said on the other FR, then I don't mind adding a way to auto-embed it.

**Comment by MrVauxs** [comment]
It's too cluttery for me, yeah. I already have it and use it for references.

**Comment by therealguy90** [comment]
Making progress here. Seems to work just fine with multiple item links, too.

![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/b126ef1c-54d1-4d5d-b752-5e1674d27e1c)

**Comment by therealguy90** [comment]
Added in latest release!
