### ISSUE TITLE
Feature request: additional server-related messaging

### ISSUE THREAD

**Issue by Digmarx** [therealguy90/foundrytodiscord#27]
**Is your feature request related to a problem? Please describe.**

Nope, the module works as it says on the box, no problems there.

This is in response to the Reddit thread [here](https://www.reddit.com/r/FoundryVTT/comments/1az6jp7/ive_created_a_script_that_sends_you_a/)

**Describe the solution you'd like**

Additional messaging related to server metrics/administration. Things like:

- Player login/logout messages ("GM Foo has logged in to Lost Mines of Phandelver")
- Include current active player count in the Discord server message; maybe a "Server is [empty/full]" notification as warranted.
- Automate the server-down message rather than require a command. Obviously if there's a system halt or a "Return to Setup" notification isn't issued in-world the module won't be able to handle this, maybe there's another way(?)

**Describe alternatives you've considered**

I've been using the python script from the Reddit thread linked above. It's fine but had me thinking there might be more possibilities.

**Additional context**
N/A

**Comment by therealguy90** [comment]
Login/Logout messages shouldn't be too difficult, but there could be a problem if someone logs out and there would be no more people on the server afterwards, since obviously, modules only work clientside, so if, for example, the last user doesn't use the logout button and instead closes the browser tab, that won't be detected, but it would be detected still if there's another user on the server when a logout happens.

It's possible to automate the server down message edit, but it's only possible to do if the admin clicks on Return to Setup (specifically the one on the world sidebar). Otherwise, I can't think of any other way to automate it. Obviously, an external script could be used, but I think it's not much of a hassle to click on Return to Setup on the sidebar.

**Comment by therealguy90** [comment]
Alright, I've got *a* solution to the tab close problem. 

I have found a small issue, though, wherein if the GM *and* module-designated player (usually the first player in alphabetical order) both logout at almost the same exact time, or both login at almost the same exact time, one of the login/logout announcements might not be sent. In actual play, this will only really be a problem when the GM reloads all clients at the same exact time, i.e. when a module setting forces a reload. I'm not too worried about it, since the goal is to monitor when a player logs in, in the case of a PBP game or a 24/7 open world.

**Comment by therealguy90** [comment]
Seems to be working alright for the use-case. I'll see if I can iron out any bugs.

![image](https://github.com/therealguy90/foundrytodiscord/assets/100253440/69e78a94-0629-427d-9117-0478e19786bf)

**Comment by Digmarx** [comment]
Looks good. FWIW in my use case any missed announcements caused by near-simultaneous login/logout are irrelevant, as 99.9% of the time that would occur around the time of a game session. Personally I'm more interested in knowing who's logging in/out in the interim between games.

**Comment by Digmarx** [comment]
Had a little play around with it and it's looking pretty slick. Cheers!

**Comment by therealguy90** [comment]
Alright, I've done enough testing and there were no major issues with this, except probably someone's browser blocking the fetch request to the webhook. Should be ready for next release.
