### ISSUE TITLE
[Feature] Ability to send whole chat log to Discord

### ISSUE THREAD

**Issue by ChasarooniZ** [therealguy90/foundrytodiscord#34]
Send Chat log to discord option would be nice

**Comment by therealguy90** [comment]
Dumping your entire chat log to Discord is something that *is* possible to do... but the size of the chat log will affect how long the dumping will take, since we can only send so many messages through a webhook before it starts rate-limiting. This could take minutes or even hours.

The upcoming changes to the API will allow anyone to do this via macro and not worry about rate limit bans, but I'm afraid this isn't a feature that could become widely-used, as Foundry to Discord is simply that, your chat log pasted onto Discord already. If you're interested in doing this, I suggest waiting for the next release where I will supply an API method to parse a ChatMessage and send it to any webhook of your choosing.

**Comment by ChasarooniZ** [comment]
Yeah allowing it to be doable via a macro/API the API is perfectly reasonable/sufficient!
