### ISSUE TITLE
It's now showing token images on discord.

### ISSUE THREAD

**Issue by Boifuba** [therealguy90/foundrytodiscord#4]
I am using the latest version of FoundryVTT and the GURPS GGA System.

The items referring to the system work very well. But the tokens/avatars images are not showing up on discord. Could you guide me how can I fix this?

![image](https://github.com/therealguy90/foundrytodiscord/assets/21176804/9475aa50-1b51-4632-9a7a-5e366708bdf6)

My server is public https://campanhasdoboi.com.br/ and i'm using it on oracle, you check by yourself. So i see no reason to no share the imgs with discord!

**Comment by therealguy90** [comment]
If the default Foundry icon is not showing, it's a sign of one of two things: your server isn't allowing access to the files on the machine it's hosted on, (which it's not, since the foundry icon appears when I visit your domain/modules/foundrytodiscord/src/defaultavatar.png), so that might mean your invite link on the config is wrong. Is that link what you put into the invite URL on your module config?

**Comment by therealguy90** [comment]
Thanks for giving me your invite link! It seems this link is working as the Game Invite URL **(Configure Settings -> Foundry to Discord -> Game Invite URL)**for Foundry to Discord to function properly, and is fetching the images as intended. Are you still having trouble with this?

**Comment by Boifuba** [comment]
Yeah, i corrected the invite. so i got some changes.
![image](https://github.com/therealguy90/foundrytodiscord/assets/21176804/209897dd-c2f9-433a-9282-8caa32cfc303)
It's getting the default avatar but not the token imagem or player avatar.

**Comment by therealguy90** [comment]
Ah, if the user's default avatar is not set, it will automaticaally default to the Foundry icon as well. Seems like your Gamemaster account has an avatar set, but the player user doesn't.

You're welcome, and enjoy!

**Comment by Boifuba** [comment]
Thank you very much, let me restart everything and set avatar correctly for everyone. If you need a server to run some tests please let me know, mine is 24/7 on oracle! Thanks for all the work and to be so kind! God bless you

**Comment by GabrielOsvair** [comment]
Hello everyone, I had the same problem with the tokens not appearing in the discord bot, and when logging into Foundry on my cell phone I realized that the Certboot certificate had expired, and that's why the webhook failed to access the server. Just stopping by to remind you to change your certificates when you renew (yes, I had forgotten to replace them).
And of course, thank you very much for the module and the great work!
