### ISSUE TITLE
Feature: Improved damage chat in D&D 5e

### ISSUE THREAD

**Issue by GabrielOsvair** [therealguy90/foundrytodiscord#5]
Suggestion: It would be interesting if it only showed "TokenName HP Updated: 11-6(6)=5".

Thanks a lot for the module! I loved.

![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/5dde236b-fbc3-4e2a-8455-80aa9b6dd5ed)
![image](https://github.com/therealguy90/foundrytodiscord/assets/67530921/1e36a2bf-b412-4278-a66b-29b8fa34915d)

**Comment by therealguy90** [comment]
As someone who doesn't play 5e, I need steps to reproduce this message. Please provide clear steps, as well as the ChatMessage object created. This is done in the console using `game.messages.get("messageID");`. Foundry logs created ChatMessage IDs in the console, so you can find the ChatMessage ID there. If determined to be easily re-formatted, your feature request will be fulfilled. If this turns out to be a module-specific chatmessage, I'll close and mark this as wontfix.

**Comment by GabrielOsvair** [comment]
The message is specific to the Midi module, so I think it can close.

**Comment by therealguy90** [comment]
If you want to assist in helping create support for midi, as it is a widely-used module, feel free to contact me in Discord and we can talk about it. I don't know the specifics of the stylings midi uses, so having someone that does would help. I would work on it on my own if I wanted to, but since midi is a feature-rich module, I wouldn't know where to start.

**Comment by GabrielOsvair** [comment]
It would be awesome! Midi is responsible for automation in D&D 5e (from the simplest to the most complex) and is widely used. I can't tomorrow, but I'll get in touch as soon as I have time.
